### ISSUE TITLE
迁移已过期的数据会不断重试,导致进程一直不退出

### ISSUE THREAD

**Issue by Ericcc1024** [openGemini/data-migration-tools#19]
<img width="629" alt="Snipaste_2024-01-02_15-42-49" src="https://github.com/openGemini/data-migration-tools/assets/56809410/e24c406e-2d5c-4d5e-878f-7106fbd82fcc">

日志打印一直在retry

**Comment by shilinlee** [comment]
Thanks. I will fix it in the next version.
